//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchidesArchitectureWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBArchidesArchitetureEntities : DbContext
    {
        public DBArchidesArchitetureEntities()
            : base("name=DBArchidesArchitetureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoria> Kategorias { get; set; }
        public virtual DbSet<Lajmi> Lajmis { get; set; }
        public virtual DbSet<LlojiArkitektura> LlojiArkitekturas { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MediaType> MediaTypes { get; set; }
        public virtual DbSet<Projekti> Projektis { get; set; }
        public virtual DbSet<ProjektiMedia> ProjektiMedias { get; set; }
        public virtual DbSet<ProjektiUser> ProjektiUsers { get; set; }
        public virtual DbSet<Roli> Rolis { get; set; }
        public virtual DbSet<Useri> Useris { get; set; }
    }
}
