//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchidesArchitectureWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medium()
        {
            this.ProjektiMedias = new HashSet<ProjektiMedia>();
        }
    
        public int MediaID { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public Nullable<int> LlojiArkitekturaID { get; set; }
        public string MediaPath { get; set; }
        public Nullable<bool> Activ { get; set; }
    
        public virtual LlojiArkitektura LlojiArkitektura { get; set; }
        public virtual MediaType MediaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektiMedia> ProjektiMedias { get; set; }
    }
}
