//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchidesArchitectureWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektiUser
    {
        public int ProjektiUserID { get; set; }
        public Nullable<int> ProjektiID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Activ { get; set; }
        public virtual Projekti Projekti { get; set; }
        public virtual Useri Useri { get; set; }
    }
}
